version: '3.9'

services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=gmweb
      - APP_USER_PASSWORD=gmweb
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s gmweb/gmweb@localhost:1521/FREEPDB1"]
      interval: 30s
      timeout: 10s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "8081:8080"

  backend:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ORACLE_HOST=oracle
      - ORACLE_PORT=1521
      - ORACLE_SERVICE=FREEPDB1
      - ORACLE_USER=gmweb
      - ORACLE_PASSWORD=gmweb
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=gmweb
      - KEYCLOAK_CLIENT_ID=gmweb-api
      - KEYCLOAK_CLIENT_SECRET=local-secret
      - LEGACY_API_URL=http://legacy:9000
    depends_on:
      - oracle
      - keycloak
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

  legacy:
    image: node:20-alpine
    command: sh -c "npx http-server --port 9000"
    working_dir: /opt/legacy
    volumes:
      - ../legacy:/opt/legacy:ro
    expose:
      - "9000"
