FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/angular.json frontend/tsconfig*.json frontend/karma.conf.js frontend/proxy.conf.json ./
COPY frontend/.browserslistrc .
COPY frontend/src ./src
RUN npm run build -- --configuration production

FROM nginx:1.25-alpine
COPY deployment/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/gmweb /usr/share/nginx/html
EXPOSE 80
