spring:
  datasource:
    url: jdbc:oracle:thin:@//${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SERVICE}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT_ID}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
legacy:
  api:
    url: ${LEGACY_API_URL}
